

name: CI


on:
  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

 
  workflow_dispatch:


jobs:
  
  build:
    
    runs-on: ubuntu-latest

 
    steps:
    
      - uses: actions/checkout@v4

  
      - name: Build image
        run: |
          docker build -t ${{secrets.REGISTRY_USER}}/my_cv_review:${{github.run_number}} .
          docker build -t ${{secrets.REGISTRY_USER}}/my_cv_review .

 
      - name: Push image
        run: |
          docker login -u ${{secrets.REGISTRY_USER}} -p ${{secrets.REGISTRY_PASS}}
          docker push ${{secrets.REGISTRY_USER}}/my_cv_review:${{github.run_number}} 
          docker push ${{secrets.REGISTRY_USER}}/my_cv_review
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH to Server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
         # port: ${{ secrets.PORT }}
          script: |
                  docker rm -f my_cv_review
                  docker run -d --name my_cv_review -p 8080:5001 ${{secrets.REGISTRY_USER}}/my_cv_review:${{github.run_number}}
